apiVersion: v1
kind: Secret
metadata:
    name: discord-template-notifier-secret
type: Opaque
stringData:
    config.toml: ENC[AES256_GCM,data:5BGfrQLUbXt1Sxsg7v4W9XAUK8xnUk7IBRJf6yd1qCtR5JnRA8qyUYYF2/aw9tXhPh57Ez1zFnBMV/+VnzpOCaVtMJ3B4h3aqByKuw7MHMFN5tU+OANHFVbm6gR1ry30DC5gaqqTULbvowAmFYSzH1rIGsa7goq9vPJunfl7bJ0cnObqmYg0AC1TlB4xRxluL4rRjKO+osOcZ3tCHp34XN+tJ9oiON5P,iv:eelX+SZ16fS38yVsRCAEODodjy/1utVn7M6WdYwUbak=,tag:UO2+231GlpcaBBJSuOzvYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wewfqn52v9scervzhypgrk2luawt5deda98gvl5u9l8frys4ms0sqqjr7a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6REZUcWJHdnpoOHMwbXEy
            Ny9SWkZ1RkkrZWtEUjU3czdGWENPRUZjRnp3CmpnUmNaTWFLeXFmbXIxc1Z4ZUc2
            UmUzR0lMY1lRTVBKQUZaQ2pIajNjOUEKLS0tIDFVOFZOdHJqVVBaN2ZzT0F0a2xh
            YWR2a3QwQXZpd0xrSUt0RXNhb1ZnM2cKUFD791+8hf6UuaR2m1zFinz2SBcm1LD4
            XsCx6IG0cE+KwyIRWvRe+OaNyuCQgeZ3jX+hz5t9/TVuFD7Zv3oRWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-22T16:11:30Z"
    mac: ENC[AES256_GCM,data:Q+A8zBw+z2DggQfibWAtsZgIFKnLXGZDhFUjEDCC6RdpsNzYtAN0h77EPqOtOUFO1KC9ztv+xW75UM40DmPGWzmX06gya36Zybf/eriMdkUBAYUKErYJcgZaxATIJvvhNMBkX7VMjIbmQDQm+UdJNtTp7rMsW7gk4ekjhkM19z0=,iv:/gAnrWncpn5GyaBw6skdNFGhkUHoyeQg4kz40vquXJ8=,tag:XgAQTgWKBrxcvcGb1r1P3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
