---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1wewfqn52v9scervzhypgrk2luawt5deda98gvl5u9l8frys4ms0sqqjr7a"
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1wewfqn52v9scervzhypgrk2luawt5deda98gvl5u9l8frys4ms0sqqjr7a"
