apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-user: ENC[AES256_GCM,data:3KXYh4I=,iv:y6UDwcDVU5vEK8ISkAX2K32izqwRi2XD/wbYh76Vbvg=,tag:BklZohbotUJ8IDFNyzQ+Mw==,type:str]
    admin-password: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wewfqn52v9scervzhypgrk2luawt5deda98gvl5u9l8frys4ms0sqqjr7a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOeTZadEpyKzFkR25KVlZu
            N0loL2FzTVJyb1AxVnVhc1FCVGRzRm5NTXhNCkcxcWY3K0NvRndGOWgrQWFVMFMz
            Y2hQVnMwamw2V0lpYjJ5Yk92dVR5TEEKLS0tIENSZFNRbWkvNUZQZThjMzRwWXRE
            S2w5SWRvL09OZVFsbG1ZSjh6YkxoRzgK5aYiC9Eu84AB+Qv5oWOjBB028EIwdui4
            zizgpQnyGW80jfgpAEpexRIIxgMcnYRtiiukb3E2We7+AVm7gdkjJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-22T16:57:53Z"
    mac: ENC[AES256_GCM,data:/aDqMKNvXyVZ//RTiZu9M/Rg3wmbMDhs/1zE743xEtBb5HDEDoq9h/A8XENQ8SpJwYm/gc+lEFg0e7OnJx5Ym/lhGI33Tf24zg+6c4yFpLl0JBJ3fkECG++Ou+0XI5lOaE4E+ITH68C+L3PG4401Cf5kKa/0Y5spYx8k01hswUk=,iv:lZ9Hyx3FVpeM3E3nt+tht4Yu+Wxu64JQ5ME8ZHyA3Cs=,tag:CDgW4Xmzk3UT+84Z7n0OyQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
