apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:66R0lPqRdU42seM9xWDTWd98EWtqChko+Q1TkVkkEEN1WC1PnR+bjw==,iv:y0HMrAOsZCoZpTTtP2c5Gw5n0CJQTKjb7UzqJm9MQ/I=,tag:9DSVlHEzVDX45IH67EIX+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wewfqn52v9scervzhypgrk2luawt5deda98gvl5u9l8frys4ms0sqqjr7a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUy9RUlJOdjM0WnI5RUt0
            SlpKOWJxUkp0cDhUdVVxMFY2eXpDcG9ud0RFCjNKMjBvZXhKdkU5aE5pdUpZOGJJ
            Y1lGVThLd3hxcGIvbVFUNkhJbnZBaG8KLS0tIHhNVUc3eVN3RXhEUllKTXd5dXNZ
            WVNOdDF4bEFkTDJXQ2svSTI2UTNVanMKkEBaACj3BPCAX9mZGZO2xh7i/IHyo6j3
            y3g0EM35JD7Fm3wspX0uMjHW1MU+Z7x9M8o94jvjL610ogHEgUx1Bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-22T16:11:30Z"
    mac: ENC[AES256_GCM,data:2CmyBuMmuFmdONgFBbI+JTlUgMBeChsTHzKHHk4Dt0M+WZ2X0lDHn3jCsuLy0PWwssce6eD/10o40ci8S+vtcJEUzX5puSN6/Bo/r62/TwANLRqShN8Cxk+yqcKAkAWmLZHXZSj5pL0Eqi4BP+b0VmBMkyudw/i1maTfquf/Mng=,iv:lOP2/h3FExBYk4c7MQvB3P0vgkEobudnsqF/TPO5qXc=,tag:Xv4RiDwvKMc0WiiIDLv8lA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
