---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "kube-nfs"
provisioner: nfs.csi.k8s.io
parameters:
  server: "192.168.1.67"
  share: "/mnt/sony/kubernetes"
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime"]
---
