apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:k5yiSuk8C/UOQFg=,iv:exzRadqAmsxgMw29qaaSkw/QoMk3q13gH3dAqpVsXoA=,tag:pQMv5cdMUgMxrCm40/71KA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:Ki2pjc73CpdCgKC8n7uAAN245AUVTCaF,iv:UQxyQiK7YUBFSCwd0yQEBVkfb/e4BySCoarmZFk7aOE=,tag:1P99LHVqXSfSfXmLAafNZQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:TsD+s2sGy+G+38/bQOeQJTpyuUBpMeM9pajv3cQ3xp+BN5LL,iv:ZkbYA3UDi+2NLhajckg09su5UhhC7RxgaWI2K5Ecnx4=,tag:3TV8WAvMGbt+iRn0g3rVwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wewfqn52v9scervzhypgrk2luawt5deda98gvl5u9l8frys4ms0sqqjr7a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMkFiUnYrZkNMNzN0ZjVx
            Rk1MbS96d2x6b1lHSFhYcjYzekJiZDFLYlRnCk41MGxOaE5CNThhRXNvZnZxeC9Q
            Vm14c3lhU2V2WHZNbUorRHlKZXJFczAKLS0tIGxaRG53QjkycmFKWVh0L0RPcFhh
            TWtmSnZUek05bWFMVEU1SjRwN3E3VHMK4/oF+CxDKbvoudbqWP3TIk/L1SKBuD78
            aKq9cWJBFR4D8esphJUNEnFwUPwv9JdZSvZ/O0T2I3CCDGJBFUzV9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-22T16:11:30Z"
    mac: ENC[AES256_GCM,data:oDih8ilSoigs1uwrScFotajElh6bZDz6OVAPPXVxQaI95YOYD7B5kIGBbPyZ/yFR0dM8i+tNEPvInta6pFX/Y2l06S//3CVZET6quEhBaTZWVPOeMhFGOb1IzC5WiEoMA2NarqQ6SDezxjqCjd9zfCb1HGPN6Mjyt9p97UxSlWM=,iv:xgAjkg4jTpxPfYQ3XxgHjhLauai9CbyZYvGHCb5mMKk=,tag:pdFKR3iubndvwAfGQdACzQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
