apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
stringData:
    HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: ENC[AES256_GCM,data:x5RfcjXh8kIL3OicvrS9TzIlWNSc/8tJmcSoZ0vzO6E=,iv:gPylBg1upo0N8rAyIpoosVsr2kt3JeowJxMmz9jQ7C4=,tag:8qp66YbVvISfqOXY/eckBA==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: ENC[AES256_GCM,data:fIGcUxVcoKq4c0zh9xEAOZRKQR+pGSeoYNOTb7siBF6VmCgT,iv:btUlJrTssRTXj7Ks78oFNZKHg2CBOg8LBaIw/2VqZKo=,tag:+QnBzDlK++IREuaAdbY1YA==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: ENC[AES256_GCM,data:YofZ6M/dNpmRLsPyrcRnHRX/hZi6l64bZVsjiFhuTvIcWhD4VAiRVQ==,iv:2eb6asZdmWXuXURXnLw4RkA1EpPXzntVLMPrAFpzc/8=,tag:7qodebrJbtLwwfrF7NpYSA==,type:str]
    HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:p4Otu90=,iv:3otb/SEd1XTyXgUeVgkD4BqRhwp9b5ZG1dbz7nwBZH8=,tag:qS3CEzzfyea90VVmlangMQ==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:sBBNEJOvAqtUdguX7dcJHSgOzzXcvBDP,iv:6BroUfQSMC+gBGJrA7cTDWef/fv8W/cJlANtPgZpqmo=,tag:Bir7LqufUAws972r3AQdyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wewfqn52v9scervzhypgrk2luawt5deda98gvl5u9l8frys4ms0sqqjr7a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybDZjYmRPdlBhOWh0dkxt
            SXM4ZnV4ZnAwWGhPM3FZTHcyS3hYVU92cmxJCk1RWGlqOTBaMWpaK1RBVDl2UWl2
            RnE5akNpaXhIRUJhRDhndWQrUUREMG8KLS0tIDdEd2doQUt4NkRGcTcrZWlNTFhT
            ajNobUQyMmxHSjlWcDB2R0d6NTFwaXcKqFLUQSzC40m/o14Eg57q4sl3Gfh8q2qE
            BEpiYI+SWcPluqCjCkJSF3MFNTllHlGNZLvO2E0AJbL+kByY/29q5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-26T18:22:37Z"
    mac: ENC[AES256_GCM,data:tw+Iq1rph6+ldsyOCzwlKmORnJQL/mxg+bja+35XCjkG86P3BvAmDqbxmmVoYENKTuFFXL25tcB2qag/zCiI3ia0+y4l0O2fyk2OavwDU0ML4PO5T8ztCGN78tc80uGV4mDigoZjvnVDOWE3GTZsu4hCb9viSPJbKLnjfy1XV04=,iv:vLozb3n6Sj9OaHT8oivG+qz4Wq1kg774liplwOJBwNI=,tag:Sry3r8xP4iKGB26CHL4V4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
