apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
stringData:
    HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: ENC[AES256_GCM,data:DLjtRlytMB/nEPA+AOgytweRiy9ckxf6xKYVkRn/GVA=,iv:Jv9ohKx2wAAYd5psMvU6sHuKzRI+weYCXO4JTOF0+6o=,tag:WtzuRiqG7r0e8hUSbI03pw==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: ENC[AES256_GCM,data:KehIcj2Dpm/m0HN1YdEchj7PbkWAjajRYLpa0KM4Yoqeeuwd,iv:7IMG6fg2H/frB95FEbRYg2dpTu/EmNnXuchqSUETwZA=,tag:MXqFHUW9S0RLbea5BuyFtg==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: ENC[AES256_GCM,data:ZpcH5sz1zyXpEuXRGo+8DF3RVM52YIeWPApKE/hlUkrHmQZr2M20pg==,iv:hKoFRP+pk4DM06yEY0Cwq51q2MQYhQ6ZNVtzl3m1g0U=,tag:DTOWiDO1Wlhyn+mnrSO/ZQ==,type:str]
    HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:9jZZmnA=,iv:6dI2yNEhEbndmiYItETcgemAWt95GLmbCoFtlqQlDLQ=,tag:s1NsQ/6U9deiU6j53i3nkA==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wewfqn52v9scervzhypgrk2luawt5deda98gvl5u9l8frys4ms0sqqjr7a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQmlKNUo0SnVnL2QzVnN1
            YzRaNTRWZEE2UzRlR3Qva0NldENYY2lXREdRCjBzaVpiRVRKeUZURWRTRUNvSHF1
            TFhyVzNYRm0yelNFSmM2eXNYZHNKbDAKLS0tIER2Ly8yY3RWSk1rNnVPRnlXTVpr
            ZDZmbllYcjNsRVFPQWQ3SVdrTk9ZL3cKtQJevYu/2BC9E2bD+3Z3IV03c3RHIT6L
            8/FK81/2aRAfsCOzLxELdVT1K4QY9qiCkZ6qO+mC+528ePo1WFMiiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-22T16:11:30Z"
    mac: ENC[AES256_GCM,data:meyF8UQXqCFiayTR0mavWlkAdjkbxxhLK/xE8290YroOWsiKV2O/Bn6MBJ7Ed90cUY5ty4dzQ4HWF8saI46ooJiKuwPjnILNIJ3LunDArg0ejw5d0Q4mUke7/Ua7kDxX9WrUP269haW1DxBpkngRLh+CvD/IMe6xy02UvGXpUp8=,iv:zoJKTpa/HqcOjpDB2A4HGwu9D7VuzX76Hf+we0xxqSY=,tag:Hlw1Ndg82SztU9r64iBy7w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
